app: cors-enabler
org: bhuvanmalik007
service: cors-enabler
provider:
  name: aws
  runtime: nodejs12.x
# you can add packaging information here
package:
  exclude:
    - node_modules/**
    - '!node_modules/node-fetch/**'

functions:
  corsEnablerLambda:
    handler: handler.corsEnabler
    events:
      - http:
          path: /unlock
          method: get
          cors: true
  corsEnablerPost:
    handler: handler.corsEnablerPost
    events:
      - http:
          path: /post
          method: post
          cors: true

plugins:
  - serverless-offline
